name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

  lint-api:
    needs: build
    defaults:
      run:
        working-directory: ./api
    steps:
      - run: npm run lint

  type-check-api:
    needs: build
    defaults:
      run:
        working-directory: ./api
    steps:
      - run: npm run type-check

  lint-ui:
    needs: build
    steps:
      - run: npm run lint

  type-check-ui:
    needs: build
    steps:
      - run: npm run type-check
