name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: "Front-end linting"
        run: npm run lint
      - name: "Front-end type-checking"
        run: npm run type-check
      - name: "Back-end linting"
        run: npm run lint
        working-directory: ./api
      - name: "Back-end type-checking"
        run: npm run type-check
        working-directory: ./api
      - name: "Back-end testing"
        run: npm run test
        working-directory: ./api
