name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [
          {
            name: "front-end",
            directory: ".",
          },
          {
            name: "back-end",
            directory: "./api",
          },
        ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
      - run: npm ci
      - name: lint ${{ matrix.package.name}}
        run: npm run lint
        working-directory: ${{ matrix.package.directory }}
      - name: type-check ${{ matrix.package.name}}
        run: npm run type-check
        working-directory: ${{ matrix.package.directory }}
      - name: test ${{ matrix.package.name }}
        run: npm run lint
        working-directory: ${{ matrix.package.directory }}
